# Generated by Django 5.0.6 on 2024-05-15 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_shoppingcart_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shopping_cart", to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"),
        ),
    ]
