# Generated by Django 5.0.6 on 2024-05-15 09:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_shoppingcart_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcartproduct",
            options={"ordering": ("product",), "verbose_name": "Продукт в корзине", "verbose_name_plural": "Продукты в корзинах"},
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="product",
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="user",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="shoppingcartproduct",
            name="amount",
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32000)], verbose_name="Количество"),
        ),
    ]
